apiVersion: 1
policies:
- orgId: 1
  receiver: slack-eservice
  group_by:
  - alertname
  - hostname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
  - receiver: slack-eservice
    object_matchers:
    - - severity
      - '='
      - critical
    group_wait: 10s
    repeat_interval: 1h
